version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    env_file:
      - .env
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - dsf-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.8
    env_file:
      - .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  dsf-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge