# Generated by Django 5.1.1 on 2024-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="description",
        ),
        migrations.RemoveField(
            model_name="request",
            name="email",
        ),
        migrations.RemoveField(
            model_name="request",
            name="status",
        ),
        migrations.RemoveField(
            model_name="request",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="request",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="request",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="request",
            name="message",
            field=models.TextField(
                default="Сообщение не указано", verbose_name="сообщение"
            ),
        ),
    ]
