# Generated by Django 5.2.17 on 2026-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('myapp', '0003_remove_request_description_remove_request_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='consent_text',
            field=models.TextField(blank=True, help_text='Текст согласия на момент отправки'),
        ),
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.location'),
        ),
        migrations.AddField(
            model_name='request',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.program'),
        ),
        migrations.AddField(
            model_name='request',
            name='source_page',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('trial_scheduled', 'Пробная назначена'), ('trial_completed', 'Пробная состоялась'), ('joined', 'Занимается'), ('declined', 'Отказ')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='request',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.traininggroup'),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='request',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
